"""add chapter and section to source

Revision ID: 096b022de674
Revises: 827a9331e5d6
Create Date: 2026-09-28 15:24:10.583276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096b022de674'
down_revision: Union[str, Sequence[str], None] = '827a9331e5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('chapter', sa.String(length=200), nullable=True))
    op.add_column('sources', sa.Column('section', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'section')
    op.drop_column('sources', 'chapter')
    # ### end Alembic commands ###
