"""Add exam configs

Revision ID: 204c58637a58
Revises: ffe78bb9ab5d
Create Date: 2026-09-29 14:55:58.393886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204c58637a58'
down_revision: Union[str, Sequence[str], None] = 'ffe78bb9ab5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_version_id', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('max_mistakes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_configs')
    # ### end Alembic commands ###
