"""add preferred language to admin user

Revision ID: 284be5f87303
Revises: 204c58637a58
Create Date: 2026-10-02 14:07:37.732007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284be5f87303'
down_revision: Union[str, Sequence[str], None] = '204c58637a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "admin_users",
    sa.Column(
        "preferred_language",
        sa.String(length=5),
        nullable=False,
        server_default="en",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'preferred_language')
    # ### end Alembic commands ###
