"""Add official samples

Revision ID: 2a9ab355a782
Revises: 9b3c3bd891e3
Create Date: 2026-09-29 14:33:05.689472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9ab355a782'
down_revision: Union[str, Sequence[str], None] = '9b3c3bd891e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('road_signs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_signs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], name=op.f('road_signs_content_version_id_fkey')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('road_signs_source_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('road_signs_pkey'))
    )
    # ### end Alembic commands ###
