"""add content version status constraint

Revision ID: 42f23a530fd4
Revises: 7ca6fd0378ed
Create Date: 2026-09-25 17:51:11.324438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42f23a530fd4'
down_revision: Union[str, Sequence[str], None] = '7ca6fd0378ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_check_constraint(
        "ck_content_versions_status",
        "content_versions",
        "status IN ("
        "'draft', "
        "'source_verified', "
        "'translation_pending', "
        "'translation_completed', "
        "'native_review', "
        "'approved', "
        "'published'"
        ")",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
