"""add admin users

Revision ID: 5e5e9cdea485
Revises: ef27f69af383
Create Date: 2026-09-27 12:18:38.209521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5e9cdea485'
down_revision: Union[str, Sequence[str], None] = 'ef27f69af383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_index(op.f('uq_active_content_version_no_module'), table_name='content_versions', postgresql_where='((available = true) AND (module_id IS NULL))')
    op.drop_index(op.f('uq_active_content_version_with_module'), table_name='content_versions', postgresql_where='((available = true) AND (module_id IS NOT NULL))')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_active_content_version_with_module'), 'content_versions', ['state_id', 'vehicle_id', 'module_id'], unique=True, postgresql_where='((available = true) AND (module_id IS NOT NULL))')
    op.create_index(op.f('uq_active_content_version_no_module'), 'content_versions', ['state_id', 'vehicle_id'], unique=True, postgresql_where='((available = true) AND (module_id IS NULL))')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
