"""add content version status

Revision ID: 7ca6fd0378ed
Revises: d3bf3555590f
Create Date: 2026-09-25 17:38:19.389081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca6fd0378ed'
down_revision: Union[str, Sequence[str], None] = 'd3bf3555590f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_versions', sa.Column('status', sa.String(length=30), nullable=False, server_default="draft"))
    op.alter_column("content_versions", "status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_versions', 'status')
    # ### end Alembic commands ###
