"""add exam config translations

Revision ID: 7d716dbedfc9
Revises: 46ca81ba587b
Create Date: 2026-10-02 19:54:31.342182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d716dbedfc9'
down_revision: Union[str, Sequence[str], None] = '46ca81ba587b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_config_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_config_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['exam_config_id'], ['exam_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_config_id', 'language', name='uq_exam_config_translation_language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('exam_config_translations')