"""add exam config translations

Revision ID: 7d716dbedfc9
Revises: 46ca81ba587b
Create Date: 2026-10-02 19:54:31.342182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d716dbedfc9'
down_revision: Union[str, Sequence[str], None] = '46ca81ba587b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_config_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_config_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['exam_config_id'], ['exam_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_config_id', 'language', name='uq_exam_config_translation_language')
    )
    op.drop_table('lesson_translations')
    op.drop_table('topic_translations')
    op.drop_table('question_option_translations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_option_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('review_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_option_id'], ['question_options.id'], name=op.f('question_option_translations_question_option_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('question_option_translations_pkey')),
    sa.UniqueConstraint('question_option_id', 'language', name=op.f('uq_question_option_translation_language'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('topic_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('review_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('topic_translations_topic_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_translations_pkey')),
    sa.UniqueConstraint('topic_id', 'language', name=op.f('uq_topic_translation_language'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('lesson_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('review_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('lesson_translations_lesson_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_translations_pkey')),
    sa.UniqueConstraint('lesson_id', 'language', name=op.f('uq_lesson_translation_language'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('exam_config_translations')
    # ### end Alembic commands ###
