"""Fix state code length

Revision ID: 827a9331e5d6
Revises: 1d87ff67abe1
Create Date: 2026-09-27 14:40:42.093446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827a9331e5d6'
down_revision: Union[str, Sequence[str], None] = '1d87ff67abe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'code',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'code',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
