"""add official sample translations

Revision ID: b15b8510851a
Revises: 90554962cf2f
Create Date: 2026-10-02 19:05:47.279749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15b8510851a'
down_revision: Union[str, Sequence[str], None] = '90554962cf2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_sample_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_sample_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['official_sample_id'], ['official_samples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('official_sample_id', 'language', name='uq_official_sample_translation_language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('official_sample_translations')
    # ### end Alembic commands ###
